spring:
  application:
    name: The-Last-Supper

  datasource:
    url: ${DB_URL:jdbc:h2:mem:test}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: ${JPA_DDI:false}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jwt:
    secret: ${SECRET_KEY}
    access-token-expire: 1000000000000
    refresh-token-expire: 10000000000000

  config:
    import: optional:file:.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: the-last-supper
